### ISSUE TITLE
Error Loading Color Scheme

### ISSUE THREAD

**Issue by MEXdave1997** [hjohnson02/Gotham-Theme#1]
Hey there. I have an issue where I can't seem to load the color scheme, with sublime complaining that it can't open the Widget - Gotham.stTheme file. I am currently using Sublime 3 under Windows 7, if that helps any bit.

![Gotham-theme Error](https://cloud.githubusercontent.com/assets/17634751/21071888/3184c0ec-be64-11e6-94e3-e87db7a9bd11.PNG) 

Thanks for reading this, and I hope to hear back with a workaround soon! Would love to start using this theme!

**Comment by 0xhjohnson** [comment]
Sorry about this I'll look into a workaround shortly

**Comment by 0xhjohnson** [comment]
Updated the README.md also to reflect the changes. Forgot to include that in the commit fix
