### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by arvi** [hjohnson02/Gotham-Theme#2]
This is great work :) I was thinking of porting it to Agila Family until I read the docs. 

I added Markdown support in Agila for all themes. You may add this also in your theme. :)

**Comment by 0xhjohnson** [comment]
Thanks you very much :) a lot of the inspiration came from you ! Yeah I changed a few things up specifically with the file icons.

I will look into adding markdown support that's a good idea. Thanks for the the support man

**Comment by arvi** [comment]
@9sevendesign you're welcome... hmmmm I'll experiment on the icons you used :stuck_out_tongue:  Haven't heard of it before :taco:

**Comment by mjwall** [comment]
> Thanks you very much :) a lot of the inspiration came from you ! Yeah I changed a few things up specifically with the file icons.
> 
> I will look into adding markdown support that's a good idea. Thanks for the the support man

@0xhjohnson did you ever get a chance to look at adding markdown support?  Thanks for the port
