### ISSUE TITLE
VS Code Support

### ISSUE THREAD

**Issue by MEXdave1997** [hjohnson02/Gotham-Theme#3]
Not really an issue, more like a question. 

I was wondering if this theme will ever be ported to Visual Studio Code. Would love to use it there, but would like to know if its possible to port it over.

**Comment by 0xhjohnson** [comment]
I can take a look into it for you. I'll get back with you. Glad you enjoy it

**Comment by 0xhjohnson** [comment]
Looks like someone already beat me to it ! 
https://marketplace.visualstudio.com/items?itemName=alireza94.theme-gotham

I'm going to go ahead and close this issue
