### ISSUE TITLE
Error loading colour scheme: Unable to open Gotham.stTheme

### ISSUE THREAD

**Issue by alexytsu** [hjohnson02/Gotham-Theme#5]
I downloaded the Gotham theme through Package Control. I am able to set the color_scheme properly but when I put "theme": "Gotham.sublime-theme", I get the following error: 

Error loading colour scheme Packages/Gotham-Theme/widgets/Widget - Gotham.stTheme: Unable to open Packages/Gotham-Theme/widgets/Widget - Gotham.stTheme

**Comment by 0xhjohnson** [comment]
Hmm okay I will look into it shortly.
